version: '3'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
    expose:
      - "8082"
      - "8083"
      - "8084"
      - "8085"
    volumes:
      - nexus-data:/nexus-data
    restart: on-failure

volumes:
  nexus-data: