version: "3"
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: abc
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: devl
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

volumes:
  postgresql:
  postgresql_data:
